extends: default

rules:
  indentation:
    spaces: 2
    indent-sequences: true
  document-start: disable
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 160
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
